### PR TITLE
Add support for 1920x1200 resolution

### PR DESCRIPTION
**Pull request by SolitudeSF**

### CODE REVIEW

**Comment by SolitudeSF** [comment]
i stitched background from 2 other resolutions, but i have two problems.

- i convert pcx to png with imagemagic to edit it in krita, then convert back. it work but the filesize is drastically bigger than other files and im guessing something about palette is off.
- ingame some part arent getting colored with players colors
image

**Comment by IvanSavenko** [comment]
Hi. For 1.3 extra resolutions will be deprecated. Instead vcmi will automatically generate assets for requested resolution.

**Comment by IvanSavenko** [comment]
> ingame some part arent getting colored with players colors

Not sure how krita works, but yeah. H3 images like this one have special configuration for palette. You should preserve original palette unless you know what you're doing

**Comment by SolitudeSF** [comment]
so, i should just wait for 1.3?

**Pull request closed without merging**
